# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoNA0Oa2yx_7srT1In2yq51Kg6HBG-FT
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/full combined dataset.csv")

df.head()

df.tail()

df.dtypes

df.info()

df.shape

df.columns

df.describe()

df.nunique()