# -*- coding: utf-8 -*-
"""Model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ9dkUn2IbZSgBXSkcJJM2IEmdfVEpYF
"""

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
df = pd.read_csv("/content/full combined dataset.csv")
drop_columns = [
    "battery_id",
    "Timestamp",
    "fault_type"
]
for col in drop_columns:
    if col in df.columns:
        df.drop(columns=col, inplace=True)
target = "Electricity_Consumed"
X = df.drop(columns=[target])
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42

)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
print(prediction)

import pandas as pd

# Load dataset
df = pd.read_csv("/content/full combined dataset.csv")

# Remove target column if present
if "Electricity_Consumed" in df.columns:
    X = df.drop(columns=["Electricity_Consumed"])
else:
    X = df.copy()

# Remove object columns that are not used for prediction
X = X.drop(columns=["battery_id", "fault_type", "Timestamp"], errors="ignore")

# Predict
prediction = model.predict(X)

# Save prediction
df["Predicted_Electricity"] = prediction

df.to_csv("prediction.csv", index=False)

print(df[["Predicted_Electricity"]].head())
print("Prediction Completed")

# ===========================
# Cost Avoidance Analysis
# ===========================

# Electricity tariff (Rs per kWh)
COST_PER_UNIT = 8.0      # Change according to your industry tariff

# Total actual electricity consumption
actual_units = df["Electricity_Consumed"].sum()

# Total predicted electricity consumption
predicted_units = df["Predicted_Electricity"].sum()

# If predicted value is greater than actual,
# assume no reduction
reduced_units = max(0, actual_units - predicted_units)

# Electricity cost before optimization
actual_cost = actual_units * COST_PER_UNIT

# Electricity cost after optimization
predicted_cost = predicted_units * COST_PER_UNIT

# Cost avoided
cost_avoided = max(0, actual_cost - predicted_cost)

# Percentage reduction
reduction_percentage = (reduced_units / actual_units) * 100 if actual_units > 0 else 0

print("\n========== Monthly Cost Avoidance Report ==========")
print(f"Total Electricity Consumption : {actual_units:.2f} kWh")
print(f"Predicted Electricity Usage   : {predicted_units:.2f} kWh")
print(f"Electricity Reduced           : {reduced_units:.2f} kWh")
print(f"Reduction Percentage          : {reduction_percentage:.2f}%")
print(f"Monthly Cost Before           : Rs.{actual_cost:.2f}")
print(f"Monthly Cost After            : Rs.{predicted_cost:.2f}")
print(f"Monthly Cost Avoided          : Rs.{cost_avoided:.2f}")

# Save report
report = pd.DataFrame({
    "Actual_Units": [actual_units],
    "Predicted_Units": [predicted_units],
    "Units_Reduced": [reduced_units],
    "Reduction_Percentage": [reduction_percentage],
    "Cost_Before": [actual_cost],
    "Cost_After": [predicted_cost],
    "Cost_Avoided": [cost_avoided]
})

report.to_csv("cost_avoidance_report.csv", index=False)

print("\nCost Avoidance Report Saved Successfully.")

# ==========================================
# Battery Energy Storage Analysis
# ==========================================

# Battery configuration
BATTERY_CAPACITY_KWH = 500.0      # Change according to your battery capacity
CHARGING_EFFICIENCY = 0.95         # 95% charging efficiency

# Energy available for storage
energy_saved = reduced_units

# Actual energy stored after charging losses
energy_stored = energy_saved * CHARGING_EFFICIENCY

# Battery State of Charge (SOC)
battery_soc = min((energy_stored / BATTERY_CAPACITY_KWH) * 100, 100)

# Number of full battery charges
full_charge_cycles = energy_stored / BATTERY_CAPACITY_KWH

# Remaining battery capacity
remaining_capacity = max(BATTERY_CAPACITY_KWH - energy_stored, 0)

print("\n========== Monthly Battery Energy Storage Report ==========")
print(f"Energy Saved                     : {energy_saved:.2f} kWh")
print(f"Battery Charging Efficiency      : {CHARGING_EFFICIENCY*100:.0f}%")
print(f"Energy Stored in Battery         : {energy_stored:.2f} kWh")
print(f"Battery Capacity                 : {BATTERY_CAPACITY_KWH:.2f} kWh")
print(f"Battery State of Charge (SOC)    : {battery_soc:.2f}%")
print(f"Equivalent Full Charge Cycles    : {full_charge_cycles:.2f}")
print(f"Remaining Battery Capacity       : {remaining_capacity:.2f} kWh")

# Save battery report
battery_report = pd.DataFrame({
    "Energy_Saved_kWh": [energy_saved],
    "Charging_Efficiency": [CHARGING_EFFICIENCY],
    "Energy_Stored_kWh": [energy_stored],
    "Battery_Capacity_kWh": [BATTERY_CAPACITY_KWH],
    "Battery_SOC_Percentage": [battery_soc],
    "Equivalent_Full_Charge_Cycles": [full_charge_cycles],
    "Remaining_Battery_Capacity_kWh": [remaining_capacity]
})

battery_report.to_csv("battery_storage_report.csv", index=False)

print("\nBattery Storage Report Saved Successfully.")