# -*- coding: utf-8 -*-
"""LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRw7Jk9TiykzfFLXQP-cXFZVK_ift57N
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping

# -----------------------------------
# Load Dataset
# -----------------------------------

df = pd.read_csv("/content/full combined dataset.csv")

# -----------------------------------
# Drop unwanted columns
# -----------------------------------

drop_columns = [
    "battery_id",
    "Timestamp",
    "fault_type"
]

for col in drop_columns:
    if col in df.columns:
        df.drop(columns=col, inplace=True)

# -----------------------------------
# Target
# -----------------------------------

target = "Electricity_Consumed"

X = df.drop(columns=[target]).values
y = df[target].values.reshape(-1,1)

# -----------------------------------
# Feature Scaling
# -----------------------------------

x_scaler = MinMaxScaler()
y_scaler = MinMaxScaler()

X = x_scaler.fit_transform(X)
y = y_scaler.fit_transform(y)

# -----------------------------------
# Create Sequences
# -----------------------------------

time_steps = 10

X_seq = []
y_seq = []

for i in range(len(X)-time_steps):
    X_seq.append(X[i:i+time_steps])
    y_seq.append(y[i+time_steps])

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

# -----------------------------------
# Train Test Split
# -----------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X_seq,
    y_seq,
    test_size=0.2,
    random_state=42
)

# -----------------------------------
# Build LSTM Model
# -----------------------------------

model = Sequential()

model.add(LSTM(
    units=64,
    activation='tanh',
    input_shape=(X_train.shape[1], X_train.shape[2])
))

model.add(Dense(32, activation='relu'))

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse'
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

# -----------------------------------
# Train Model
# -----------------------------------

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# -----------------------------------
# Prediction
# -----------------------------------

prediction = model.predict(X_test)

prediction = y_scaler.inverse_transform(prediction)
y_test_actual = y_scaler.inverse_transform(y_test)

# -----------------------------------
# Evaluation
# -----------------------------------

mae = mean_absolute_error(y_test_actual, prediction)

mse = mean_squared_error(y_test_actual, prediction)

rmse = np.sqrt(mse)

r2 = r2_score(y_test_actual, prediction)

accuracy = r2 * 100

print("\n==============================")

print("R2 Score :", round(r2,4))

print("Accuracy :", round(accuracy,2),"%")

print("MAE :", round(mae,4))

print("RMSE :", round(rmse,4))

print("==============================")

# -----------------------------------
# Save Model
# -----------------------------------

model.save("LSTM_Electricity_Model.h5")

joblib.dump(x_scaler,"x_scaler.pkl")
joblib.dump(y_scaler,"y_scaler.pkl")

print("LSTM Model Saved Successfully")