# -*- coding: utf-8 -*-
"""Random Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jzb3doHCpTqHZ-inCYQpK5eiWwPlZ6W
"""

import pandas as pd
import joblib

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from xgboost import XGBRegressor

# -----------------------------
# Load Dataset
# -----------------------------

df = pd.read_csv("/content/full combined dataset.csv")

# -----------------------------
# Drop unwanted columns
# -----------------------------

drop_columns = [
    "battery_id",
    "Timestamp",
    "fault_type"
]

for col in drop_columns:
    if col in df.columns:
        df.drop(columns=col, inplace=True)

# -----------------------------
# Target
# -----------------------------

target = "Electricity_Consumed"

X = df.drop(columns=[target])

y = df[target]

# -----------------------------
# Train Test Split
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# -----------------------------
# XGBoost Model
# -----------------------------

model = RandomForestRegressor(

    n_estimators=300,

    max_depth=20,

    min_samples_split=2,

    min_samples_leaf=1,

    random_state=42,

    n_jobs=-1

)

model.fit(X_train, y_train)

# -----------------------------
# Prediction
# -----------------------------

prediction = model.predict(X_test)

# -----------------------------
# Evaluation
# -----------------------------

mae = mean_absolute_error(y_test, prediction)

mse = mean_squared_error(y_test, prediction)

rmse = mse ** 0.5

r2 = r2_score(y_test, prediction)

accuracy = r2 * 100

print("\n==============================")

print("R2 Score :", round(r2,4))

print("Accuracy :", round(accuracy,2),"%")

print("MAE :", round(mae,4))

print("RMSE :", round(rmse,4))

print("==============================")
print("Model Saved Successfully")