# -*- coding: utf-8 -*-
"""SARIMAX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StWlDRJVhqpVms-fVlV6P_W1Dlg6YYKZ
"""

import pandas as pd
import joblib

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from statsmodels.tsa.statespace.sarimax import SARIMAX

# -----------------------------
# Load Dataset
# -----------------------------

df = pd.read_csv("/content/full combined dataset.csv")

# -----------------------------
# Convert Timestamp to Datetime
#
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

df = df.sort_values("Timestamp")

df.set_index("Timestamp", inplace=True)

# -----------------------------
# Target Variable
# -----------------------------

target = "Electricity_Consumed"

# -----------------------------
# Available Feature Columns
# -----------------------------

features = [
    "Temperature",
    "Humidity",
    "Wind_Speed",
    "Avg_Past_Consumption"
]

# Keep only columns that actually exist
features = [col for col in features if col in df.columns]

# -----------------------------
# Remove Missing Values
# -----------------------------

df = df[[target] + features].dropna()

# -----------------------------
# Train-Test Split
# -----------------------------

train_size = int(len(df) * 0.80)

train = df.iloc[:train_size]

test = df.iloc[train_size:]

# -----------------------------
# Build SARIMAX Model
# -----------------------------

model = SARIMAX(
    train[target],
    exog=train[features],
    order=(2,1,2),
    seasonal_order=(1,1,1,24),
    enforce_stationarity=False,
    enforce_invertibility=False
)

model_fit = model.fit(disp=False)

# -----------------------------
# Prediction
# -----------------------------

prediction = model_fit.predict(
    start=test.index[0],
    end=test.index[-1],
    exog=test[features]
)

# -----------------------------
# Evaluation
# -----------------------------

mae = mean_absolute_error(test[target], prediction)

mse = mean_squared_error(test[target], prediction)

rmse = mse ** 0.5

r2 = r2_score(test[target], prediction)

accuracy = r2 * 100

print("\n==============================")

print("R2 Score :", round(r2, 4))

print("Accuracy :", round(accuracy, 2), "%")

print("MAE :", round(mae, 4))

print("RMSE :", round(rmse, 4))

print("==============================")

# -----------------------------
# Save Model
# -----------------------------

joblib.dump(model_fit, "sarimax_model.pkl")

print("\nSARIMAX Model Saved Successfully")